services:
  - type: web
    name: store-bot
    env: python
    buildCommand: |
      curl -fsSL https://pyenv.run | bash
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init --path)"
      pyenv install 3.11.0
      pyenv local 3.11.0
      pip install --upgrade pip setuptools
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8966604433:AAEAxUlW0Nk44mck3uioqWszYQuYzJyyyW0
      - key: PYTHON_VERSION
        value: 3.11.0
